
package net.lookup.person;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "PersonLookup", targetNamespace = "http://person.lookup.net/", wsdlLocation = "http://192.168.56.1:7001/LookupWS/PersonLookup?WSDL")
public class PersonLookup_Service
    extends Service
{

    private final static URL PERSONLOOKUP_WSDL_LOCATION;
    private final static WebServiceException PERSONLOOKUP_EXCEPTION;
    private final static QName PERSONLOOKUP_QNAME = new QName("http://person.lookup.net/", "PersonLookup");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://192.168.56.1:7001/LookupWS/PersonLookup?WSDL");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        PERSONLOOKUP_WSDL_LOCATION = url;
        PERSONLOOKUP_EXCEPTION = e;
    }

    public PersonLookup_Service() {
        super(__getWsdlLocation(), PERSONLOOKUP_QNAME);
    }

    public PersonLookup_Service(WebServiceFeature... features) {
        super(__getWsdlLocation(), PERSONLOOKUP_QNAME, features);
    }

    public PersonLookup_Service(URL wsdlLocation) {
        super(wsdlLocation, PERSONLOOKUP_QNAME);
    }

    public PersonLookup_Service(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, PERSONLOOKUP_QNAME, features);
    }

    public PersonLookup_Service(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public PersonLookup_Service(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns PersonLookup
     */
    @WebEndpoint(name = "PersonLookupPort")
    public PersonLookup getPersonLookupPort() {
        return super.getPort(new QName("http://person.lookup.net/", "PersonLookupPort"), PersonLookup.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns PersonLookup
     */
    @WebEndpoint(name = "PersonLookupPort")
    public PersonLookup getPersonLookupPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://person.lookup.net/", "PersonLookupPort"), PersonLookup.class, features);
    }

    private static URL __getWsdlLocation() {
        if (PERSONLOOKUP_EXCEPTION!= null) {
            throw PERSONLOOKUP_EXCEPTION;
        }
        return PERSONLOOKUP_WSDL_LOCATION;
    }

}
